id: IAEC195C9
legacy_id: P000537
ocr_import_info:
  bdrc_scan_id: W1PD181173
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T12:44:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T04:16:52.308937+00:00'
last_modified: 2022-09-01 12:17:23.124915
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD181173
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1PD181173
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྔ་འགྱུར་གཡག་ཟེའི་གཏེར་སྟོན་བདེ་མཆོག་གླིང་པའི་གཏེར་ཆོས།
  author: གཡག་ཟེ་གཏེར་སྟོན་བདེ་མཆོག་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.5322227012117995
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I1KG16340:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16340
      total_pages: 702
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16340.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5440085683273878
    legacy_id: v001
  I1KG16341:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16341
      total_pages: 1016
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG16341.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5234424753621324
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
